sudo: required

language: node_js
node_js:
  - "5"

services:
  - docker

install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t containx/depcon-site .
  - docker run -d -p 127.0.0.1:80:80 --name depcon containx/depcon-site

script:
  - docker ps | grep -q depcon

after_success:
  - docker push containx/depcon-site
  - docker run -e DEPCON_MODE=$DEPCON_MODE -e MARATHON_HOST=$MARATHON_HOST -e MARATHON_USER=$MARATHON_USER -e MARATHON_PASS=$MARATHON_PASS -v $PWD:/data pacesys/depcon app create /data/depcon.yml --wait --force

# whitelist
branches:
  only:
    - master
